import type { Metadata } from "next";
import "@/presentation/styles/globals.css";
import { asap } from "@/presentation/assets/fonts";
import { DIConfig } from "@/config/di";

export const metadata: Metadata = {
  title: "Portifólio de Ikaro Montanari",
  description: "Generated by create next app",
};

DIConfig.config();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={asap.className}>{children}</body>
    </html>
  );
}
