import type { Metadata } from "next";
import "../styles/globals.css";
import { asap } from "@/assets/fonts";


export const metadata: Metadata = {
  title: "Portifólio de Ikaro Montanari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={asap.className}>{children}</body>
    </html>
  );
}
